"""Initial migration.

Revision ID: 96a290316a81
Revises: 
Create Date: 2024-06-16 00:32:33.452214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96a290316a81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erreur_solutions')
    op.drop_table('erreur_outils')
    op.drop_table('messages')
    op.drop_table('erreurs')
    op.drop_table('solutions')
    op.drop_table('requetes')
    op.drop_table('logs_interactions')
    op.drop_table('conversations')
    op.drop_table('outils')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outils',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('lien', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('conversations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('logs_interactions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('interaction', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('requetes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('reponse', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('solutions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('erreurs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('source', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('conversation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sender', mysql.ENUM('user', 'bot'), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='messages_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('erreur_outils',
    sa.Column('erreur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('outil_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['erreur_id'], ['erreurs.id'], name='erreur_outils_ibfk_1'),
    sa.ForeignKeyConstraint(['outil_id'], ['outils.id'], name='erreur_outils_ibfk_2'),
    sa.PrimaryKeyConstraint('erreur_id', 'outil_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('erreur_solutions',
    sa.Column('erreur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('solution_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['erreur_id'], ['erreurs.id'], name='erreur_solutions_ibfk_1'),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name='erreur_solutions_ibfk_2'),
    sa.PrimaryKeyConstraint('erreur_id', 'solution_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
